### ISSUE TITLE
What about individual sponsors?

### ISSUE THREAD

**Issue by prijindal** [ossfriendly/open-source-supporters#19]
Individual sponsors contributes to a significant amount of open source finding.
Will there be another section for those kind of developers?

**Comment by kof** [comment]
You mean like a person investing using tools like opencollective, right? For sure we could list such a person, but what sense would it make? We are ultimately trying to improve the industry.

**Comment by staltz** [comment]
Yeah, we are discussing that in #22, but the idea with this list isn't to necessarily thank all the sponsors (individuals or companies), it's primarily to create a "*you better be on this list if you're a company*" effect. I myself receive sponsorship from individuals so I can do open source, and I'm immensely thankful for them. It's just a different concern to this list.

**Comment by staltz** [comment]
(Can reopen, let's just see if we can discuss this elsewhere, since there are similar issues)
