### ISSUE TITLE
Does Microsoft qualify?

### ISSUE THREAD

**Issue by molant** [ossfriendly/open-source-supporters#48]
[Microsoft is member of the Linux foundation and contributes to numerous third party projects](https://www.linuxfoundation.org/announcements/microsoft-fortifies-commitment-to-open-source-becomes-linux-foundation-platinum) but it is not in the list.
Is the criteria in the article good enough to open a PR?

**Comment by jdreesen** [comment]
There's already a discussion here: #39

**Comment by molant** [comment]
Thanks!
