### ISSUE TITLE
Why is this list grouped by countries?

### ISSUE THREAD

**Issue by jankeromnes** [ossfriendly/open-source-supporters#7]
I believe it doesn't mean much for global organizations, e.g. Google and Mozilla, who sponsor open source projects everywhere.

**Comment by staltz** [comment]
It's grouped by country so the IT industry in each country can have a reference on which companies give back to open source, either for recruitment or marketing. Global companies exist, but they are the exception more than the norm, and often one of the countries hosts the headquarters, with a massive influence on culture (I would definitely classify Google a USA company). Hard to find a case of a company that is truly uniformly spread across countries with none playing a central role.
